# Set theme
theme: alembic-jekyll-theme


# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

include:
- pics
- css/custom.css

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://plamka-ilieva.com'
baseurl: ''
title: 'Plamka Ilieva'
description: 'Център за професионално обучение към „ИТИ – Пламка Георгиева” – гр. Монтана'
permalink: pretty
logo: "/pics/logo.png"
encoding: utf-8

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Начало
  url: /
- title: За нас
  url: /about/
- title: Курсове
  url: /courses/
- title: Ваучерно обучение
  url: /voucher-training/
- title: Галерия
  url: /gallery/
- title: Контакти
  url: /contact/

# Footer nav
navigation_footer:
- title: 
  url: /


# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
